
const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';

const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
const LOAD_CATEGORIES_SUCCESS = 'LOAD_CATEGORIES_SUCCESS';





const API_CALL_ERROR = 'API_CALL_ERROR';

export { 
    //auth
    AUTH_LOGIN_SUCCESS, 
    AUTH_LOGOUT_SUCCESS,

    LOAD_CATEGORIES_SUCCESS,
    LOAD_PRODUCTS_SUCCESS,

    //api    
    API_CALL_ERROR
}